fix(PR): Removed excess target frameworks and reverted Assembly signing
Assembly signing failed because of
error CS8002: Referenced assembly 'ClickHouse.Driver, Version=0.7.20.0, Culture=neutral, PublicKeyToken=null' does not have a strong name